
const MENU_DATA = [
  {
    id: "huevos-con-nopales",
    nombre: "Huevos con nopales",
    descripcion: "2 huevos estrellados acompañados de frijoles.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "huevos-al-albanil",
    nombre: "Huevos al albañil",
    descripcion: "2 huevos con chile serrano y cebolla, acompañados de frijoles.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "huevos-al-gusto",
    nombre: "Huevos al gusto",
    descripcion: "2 huevos, elige: jamón, chorizo, salchicha o tocino.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "huevos-rancheros",
    nombre: "Huevos rancheros",
    descripcion: "Acompañados de pico de gallo y frijoles refritos.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "huevos-a-la-mexicana",
    nombre: "Huevos a la mexicana",
    descripcion: "2 huevos con jitomate, cebolla, chile y cilantro, acompañados de frijoles.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "huevos-divorciados",
    nombre: "Huevos divorciados",
    descripcion: "2 huevos bañados en salsa verde y roja, acompañados de frijoles.",
    precio: 150,
    categoria: "huevos",
  },
  {
    id: "omelette-de-jamon-y-queso",
    nombre: "Omelette de jamón y queso",
    descripcion: "Omelette relleno de jamón y queso, acompañado de frijoles.",
    precio: 135,
    categoria: "omelettes",
  },
  {
    id: "omelette-de-salchicha",
    nombre: "Omelette de salchicha",
    descripcion: "Omelette relleno de salchicha, acompañado de frijoles.",
    precio: 135,
    categoria: "omelettes",
  },
  {
    id: "omelette-de-3-quesos",
    nombre: "Omelette de 3 quesos",
    descripcion: "Omelette relleno de tres tipos de queso, acompañado de frijoles.",
    precio: 140,
    categoria: "omelettes",
  },
  {
    id: "omelette-con-espinaca",
    nombre: "Omelette con espinaca",
    descripcion: "Omelette relleno de espinaca fresca, acompañado de frijoles.",
    precio: 140,
    categoria: "omelettes",
  },
  {
    id: "omelette-con-champiñones",
    nombre: "Omelette con champiñones",
    descripcion: "Omelette relleno de champiñones frescos, acompañado de frijoles.",
    precio: 140,
    categoria: "omelettes",
  },
  {
    id: "chilaquiles-con-huevo",
    nombre: "Chilaquiles con huevo",
    descripcion: "Totopos de maíz con salsa, 2 huevos y acompañados de frijoles.",
    precio: 135,
    categoria: "chilaquiles",
  },
  {
    id: "chilaquiles-con-pollo",
    nombre: "Chilaquiles con pollo",
    descripcion: "Totopos de maíz con salsa, pollo deshebrado, 2 huevos y frijoles.",
    precio: 140,
    categoria: "chilaquiles",
  },
  {
    id: "chilaquiles-con-arrachera",
    nombre: "Chilaquiles con arrachera",
    descripcion: "Totopos de maíz con salsa, arrachera, 2 huevos y frijoles.",
    precio: 150,
    categoria: "chilaquiles",
  },
  {
    id: "chilaquiles-con-bistec",
    nombre: "Chilaquiles con bistec",
    descripcion: "Totopos de maíz con salsa, bistec a la plancha, 2 huevos y frijoles.",
    precio: 150,
    categoria: "chilaquiles",
  },
  {
    id: "enchiladas-con-pollo",
    nombre: "Enchiladas con pollo",
    descripcion: "4 piezas, verdes o rojas.",
    precio: 200,
    categoria: "enchiladas",
  },
  {
    id: "enchiladas-con-bistec",
    nombre: "Enchiladas con bistec",
    descripcion: "4 piezas, verdes o rojas.",
    precio: 200,
    categoria: "enchiladas",
  },
  {
    id: "enchiladas-con-arrachera",
    nombre: "Enchiladas con arrachera",
    descripcion: "4 piezas, verdes o rojas.",
    precio: 220,
    categoria: "enchiladas",
  },
  {
    id: "enchiladas-suizas",
    nombre: "Enchiladas suizas",
    descripcion: "4 piezas, verdes o rojas.",
    precio: 200,
    categoria: "enchiladas",
  },
  {
    id: "tacos-dorados-de-pollo",
    nombre: "Tacos dorados de pollo",
    descripcion: "4 tacos dorados rellenos de pollo deshebrado, acompañados de crema, queso y lechuga.",
    precio: 120,
    categoria: "enchiladas",
  },
  {
    id: "quesadillas",
    nombre: "Quesadillas",
    descripcion: "3 piezas acompañadas de guacamole.",
    precio: 120,
    categoria: "enchiladas",
  },
   {
    id: "consome-o-arroz",
    nombre: "Consomé o arroz",
    descripcion: "Sopa de consome o arroz",
    precio: 150,
    categoria: "consome-o-arroz",
  },
  {
    id: "sopa-azteca",
    nombre: "Sopa azteca",
    descripcion: "Sopa tradicional de la casa, caldosa y sabrosa.",
    precio: 200,
    categoria: "consome-o-arroz",
  },

  {
    id: "guacamole",
    nombre: "Guacamole",
    descripcion: "Acompañado de totopos.",
    precio: 200,
    categoria: "platillos",
  },
  {
    id: "bistec-a-la-mexicana",
    nombre: "Bistec a la mexicana",
    descripcion: "Acompañado de jitomate, cebolla, cilantro y chile serrano con frijoles.",
    precio: 200,
    categoria: "bistec-y-pechuga",
  },
  {
    id: "bistec-encebollado",
    nombre: "Bistec encebollado",
    descripcion: "Acompañado de frijoles.",
    precio: 200,
    categoria: "bistec-y-pechuga",
  },
  {
    id: "pechuga-a-la-mexicana",
    nombre: "Pechuga a la mexicana",
    descripcion: "Acompañado de jitomate, cebolla, cilantro y chile serrano con frijoles.",
    precio: 200,
    categoria: "bistec-y-pechuga",
  },
  {
    id: "pechuga-asada",
    nombre: "Pechuga asada",
    descripcion: "Acompañada de frijoles y ensalada.",
    precio: 200,
    categoria: "bistec-y-pechuga",
  },
  {
    id: "pechuga-empanizada",
    nombre: "Pechuga empanizada",
    descripcion: "Acompañado de frijoles, ensalada y arroz.",
    precio: 200,
    categoria: "bistec-y-pechuga",
  },
  {
    id: "queso-fundido",
    nombre: "Queso fundido",
    descripcion: "Acompañado de chorizo, champiñones y pimientos, con tortillas al centro.",
    precio: 200,
    categoria: "platillos",
  },
  {
    id: "queso-fundido-con-chistorra",
    nombre: "Queso fundido con Chistorra",
    descripcion: "Acompañado con tortillas al centro.",
    precio: 250,
    categoria: "platillos",
  },
  {
    id: "queso-fundido-con-arrachera",
    nombre: "Queso fundido con Arrachera",
    descripcion: "Acompañado con tortillas al centro.",
    precio: 250,
    categoria: "platillos",
  },
  {
    id: "hamburguesa-classic",
    nombre: "Classic",
    descripcion: "Hamburguesa clásica con queso, lechuga y tomate.",
    precio: 139,
    categoria: "hamburguesas",
  },
  {
    id: "hamburguesa-arrachera",
    nombre: "Hamburguesa arrachera",
    descripcion: "Hamburguesa con arrachera, queso y aderezo de la casa.",
    precio: 250,
    categoria: "hamburguesas",
  },
  {
    id: "hamburguesa-queso-tocino",
    nombre: "Hamburguesa Queso/Tocino",
    descripcion: "Hamburguesa con queso y tocino a la parrilla.",
    precio: 200,
    categoria: "hamburguesas",
  },
  {
    id: "hamburguesa-mushroom",
    nombre: "Hamburguesa Mushroom",
    descripcion: "Hamburguesa con champiñones, queso y sazón especial.",
    precio: 200,
    categoria: "hamburguesas",
  },
  {
    id: "cortes-arrachera",
    nombre: "Arrachera",
    descripcion: "Corte de arrachera a la plancha.",
    precio: 300,
    categoria: "cortes",
  },
  {
    id: "cortes-bistec",
    nombre: "Bistec",
    descripcion: "Corte de bistec, jugoso y sabroso.",
    precio: 320,
    categoria: "cortes",
  },
  {
    id: "cortes-ribay",
    nombre: "Ribay",
    descripcion: "Corte ribay con sabor intenso y textura premium.",
    precio: 350,
    categoria: "cortes",
  },
  {
    id: "alambres-arrachera",
    nombre: "Arrachera",
    descripcion: "Alambre de arrachera con queso y salsa.",
    precio: 200,
    categoria: "alambres",
  },
  {
    id: "alambres-bistec",
    nombre: "Bistec",
    descripcion: "Alambre de bistec con queso, cebolla y chile.",
    precio: 200,
    categoria: "alambres",
  },
  {
    id: "alambres-pollo",
    nombre: "Pollo",
    descripcion: "Alambre de pollo con quesillo y sazón.",
    precio: 200,
    categoria: "alambres",
  },
  {
    id: "burritos-arrachera",
    nombre: "Arrachera",
    descripcion: "Burrito de arrachera con sabor tradicional.",
    precio: 200,
    categoria: "burritos",
  },
  {
    id: "burritos-pollo",
    nombre: "Pollo",
    descripcion: "Burrito de pollo con guarnición y salsa.",
    precio: 200,
    categoria: "burritos",
  },
  {
    id: "burritos-bistec",
    nombre: "Bistec",
    descripcion: "Burrito de bistec con sabor casero.",
    precio: 200,
    categoria: "burritos",
  },
  {
    id: "club-sandwich",
    nombre: "Club Sandwich",
    descripcion: "Sándwich de 4 capas con jamón, pollo, tocino, jitomate y lechuga, acompañado de papas fritas.",
    precio: 150,
    categoria: "sandwiches",
  },
  {
    id: "jamon-y-queso",
    nombre: "Jamón y Queso",
    descripcion: "Sándwich de 3 capas con jamón, queso, jitomate y lechuga, acompañado de papas a la francesa.",
    precio: 125,
    categoria: "sandwiches",
  },
  {
    id: "pavo",
    nombre: "Pavo",
    descripcion: "Sándwich de 3 capas con jamón de pavo, jitomate y lechuga, acompañado de papas a la francesa.",
    precio: 140,
    categoria: "sandwiches",
  },
  {
    id: "vikingo",
    nombre: "Vikingo",
    descripcion: "Sándwich con jamón, queso, jitomate y lechuga, acompañado de papas a la francesa.",
    precio: 120,
    categoria: "sandwiches",
  },
  {
    id: "viernes-y-sabado",
    nombre: "Viernes y Sábado",
    descripcion: "Especialidades tradicionales: Pancita, Pozole de puerco rojo o Mole poblano con 1 pieza de pollo (muslo o pierna).",
    precio: 150,
    categoria: "platillos-tradicionales",
  },
  {
    id: "pasta-alfredo",
    nombre: "Pasta alfredo",
    descripcion: "Pasta con salsa alfredo, queso parmesano y pimienta.",
    precio: 300,
    categoria: "pastas",
  },
  {
    id: "pasta-bolognesa",
    nombre: "Pasta a la bolognesa",
    descripcion: "Pasta con salsa de carne, tomate y especias.",
    precio: 300,
    categoria: "pastas",
  },
   {
    id: "pasta-carbonara",
    nombre: "Pasta a la carbonara",
    descripcion: "Pasta con salsa de huevo, queso parmesano y bacon.",
    precio: 300,
    categoria: "pastas",
  },
  {
    id: "molcajete-de-carne-dos-personas",
    nombre: "Molcajete de carne para dos personas",
    descripcion: "Acompañado de arrachera, pollo, chorizo, nopales, cebolla, queso, salsas y tortillas al centro.",
    precio: 600,
    categoria: "para-compartir",
  },
  {
    id: "molcajete-de-carne-cuatro-personas",
    nombre: "Molcajete de carne para cuatro personas",
    descripcion: "Parrillada para compartir carnes, chorizo, nopales, cebolla, queso, salsas y tortillas al centro.",
    precio: 720,
    categoria: "para-compartir",
  },
  {
    id: "parrilla-de-carne-dos-personas",
    nombre: "Parrillada de carnes para dos personas",
    descripcion: "Selección de carnes con guarnición y tortillas.",
    precio: 600,
    categoria: "para-compartir",
  },
  {
    id: "parrilla-de-carne-cuatro-personas",
    nombre: "Parrillada de carnes para cuatro personas",
    descripcion: "Parrillada completa para compartir con carne, chorizo y nopales.",
    precio: 1000,
    categoria: "para-compartir",
  },
  {
    id: "parrilla-de-corte-para-dos",
    nombre: "Parrillada de corte para dos personas",
    descripcion: "Cortes premium con salsa y guarnición.",
    precio: 1000,
    categoria: "para-compartir",
  },
  {
    id: "parrilla-de-corte-para-cuatro",
    nombre: "Parrillada de corte para cuatro personas",
    descripcion: "Selección especial de cortes para compartir.",
    precio: 1300,
    categoria: "para-compartir",
  },

  {
    id: "6-alitas",
    nombre: "6 alitas",
    descripcion: "Salsa a elegir + bastones de zanahoria y apio + aderezo.",
    precio: 119,
    categoria: "antojo-de-la-casa",
  },
  {
    id: "10-alitas",
    nombre: "10 alitas",
    descripcion: "Salsa a elegir + bastones de zanahoria y apio + aderezo.",
    precio: 195,
    categoria: "antojo-de-la-casa",
  },
  {
    id: "15-alitas",
    nombre: "15 alitas",
    descripcion: "Salsa a elegir + bastones de zanahoria y apio + aderezo.",
    precio: 293,
    categoria: "antojo-de-la-casa",
  },
  {
    id: "20-alitas",
    nombre: "20 alitas",
    descripcion: "Salsa a elegir + bastones de zanahoria y apio + aderezo.",
    precio: 390,
    categoria: "antojo-de-la-casa",
  },
  {
    id: "30-alitas",
    nombre: "30 alitas",
    descripcion: "Salsa a elegir + bastones de zanahoria y apio + aderezo.",
    precio: 585,
    categoria: "antojo-de-la-casa",
  },
  {
    id: "boneless-200g",
    nombre: "Boneless 200g",
    descripcion: "Acompañados de salsa BBQ, Búfalo, Mango-Habanero, Limón-Pimienta y la de la casa.",
    precio: 120,
    categoria: "boneless",
  },
  {
    id: "boneless-500g",
    nombre: "Boneless 500g",
    descripcion: "Acompañados de salsa BBQ, Búfalo, Mango-Habanero, Limón-Pimienta y la de la casa.",
    precio: 210,
    categoria: "boneless",
  },
  {
    id: "boneless-1kg",
    nombre: "Boneless 1Kg",
    descripcion: "Acompañados de salsa BBQ, Búfalo, Mango-Habanero, Limón-Pimienta y la de la casa.",
    precio: 380,
    categoria: "boneless",
  },
  {
    id: "papas-a-la-francesa",
    nombre: "Papas a la francesa",
    descripcion: "Porción individual.",
    precio: 70,
    categoria: "snacks",
  },
  {
    id: "papas-a-la-francesa-compa",
    nombre: "Papas a la francesa (para compartir)",
    descripcion: "Porción para compartir.",
    precio: 120,
    categoria: "snacks",
  },
  {
    id: "papas-gajo-porcion-individual",
    nombre: "Papas gajo porción individual",
    descripcion: "Con aderezo de la casa.",
    precio: 80,
    categoria: "snacks",
  },
  {
    id: "papas-gajo-para-compartir",
    nombre: "Papas gajo para compartir",
    descripcion: "Con aderezo de la casa.",
    precio: 140,
    categoria: "snacks",
  },
  {
    id: "papas-paulita",
    nombre: "Papas Paulita",
    descripcion: "Papas con queso derretido, tocino y jalapeño.",
    precio: 160,
    categoria: "snacks",
  },
  {
    id: "nachos-sencillos",
    nombre: "Nachos sencillos",
    descripcion: "Acompañados de queso, frijoles y jalapeños.",
    precio: 110,
    categoria: "snacks",
  },
  {
    id: "nachos-con-pollo",
    nombre: "Nachos con pollo",
    descripcion: "Acompañados de queso, frijoles y jalapeños.",
    precio: 150,
    categoria: "snacks",
  },
  {
    id: "nachos-paulita",
    nombre: "Nachos Paulita",
    descripcion: "Totopos, queso, frijoles, jalapeños, pico de gallo y crema.",
    precio: 160,
    categoria: "snacks",
  },
  {
    id: "nachos-con-bistec",
    nombre: "Nachos con bistec",
    descripcion: "Acompañados de queso, frijoles y jalapeños.",
    precio: 180,
    categoria: "snacks",
  },
  {
    id: "combo-solista",
    nombre: "Combo Solista",
    descripcion: "10 alitas + papas a la francesa + refresco.",
    precio: 210,
    categoria: "combos-guateque",
  },
  {
    id: "combo-pareja",
    nombre: "Combo Pareja",
    descripcion: "20 alitas + papas a la francesa + 2 refrescos.",
    precio: 420,
    categoria: "combos-guateque",
  },
  {
    id: "combo-cuates",
    nombre: "Combo Cuates",
    descripcion: "20 alitas + papas a la francesa + 4 cervezas nacionales.",
    precio: 499,
    categoria: "combos-guateque",
  },
  {
    id: "combo-paulita",
    nombre: "Combo Paulita",
    descripcion: "15 alitas + 500g de boneless + nachos + papas a la francesa + 4 bebidas.",
    precio: 750,
    categoria: "combos-guateque",
  },
  {
    id: "combo-guateque",
    nombre: "Combo Guateque",
    descripcion: "500g de boneless + papas gajo + 2 bebidas.",
    precio: 420,
    categoria: "combos-guateque",
  },
  {
    id: "cubeta-paulita-6-cervezas",
    nombre: "Cubeta Paulita 6 cervezas",
    descripcion: "Corona o Especial.",
    precio: 210,
    categoria: "paquetes-cerveza",
  },
  {
    id: "cubeta-premium-6-cervezas",
    nombre: "Cubeta Premium 6 cervezas",
    descripcion: "Corona Extra.",
    precio: 230,
    categoria: "paquetes-cerveza",
  },
  {
    id: "cubeta-mixta-6-cervezas",
    nombre: "Cubeta Mixta 6 cervezas",
    descripcion: "Modelo Especial o Corona Extra.",
    precio: 210,
    categoria: "paquetes-cerveza",
  },

  {
    id: "refrescos",
    nombre: "Refrescos",
    descripcion: "Variedad de refrescos de la casa.",
    precio: 35,
    categoria: "bebidas",
  },
  {
    id: "agua-de-sabor-1-litro",
    nombre: "Agua de sabor de 1 litro",
    descripcion: "Selección de aguas de sabor.",
    precio: 80,
    categoria: "bebidas",
  },
  {
    id: "agua-de-sabor-1-2-litro",
    nombre: "Agua de sabor de 1/2 litro",
    descripcion: "Selección de aguas de sabor.",
    precio: 40,
    categoria: "bebidas",
  },
  {
    id: "cafe-con-leche",
    nombre: "Café con leche",
    descripcion: "Selección de cafés con leche.",
    precio: 60,
    categoria: "bebidas",
  },
  {
    id: "chocolate-caliente",
    nombre: "Chocolate caliente",
    descripcion: "Bebida caliente de chocolate, preparada de forma tradicional.",
    precio: 60,
    categoria: "bebidas",
  },
  {
    id: "capuchino",
    nombre: "Capuchino",
    descripcion: "Café espresso con leche vaporizada y crema de leche.",
    precio: 60,
    categoria: "bebidas",
  },
  {
    id: "cerveza-de-litro",
    nombre: "Cerveza de litro",
    descripcion: "Selección de cervezas.",
    precio: 110,
    categoria: "bebidas",
  },
  {
    id: "cerveza-de-medio-litro",
    nombre: "Cerveza de medio litro",
    descripcion: "Selección de cervezas.",
    precio: 60,
    categoria: "bebidas",
  },
  {
    id: "cerveza-nacional",
    nombre: "Cerveza Nacional",
    descripcion: "Corona, Victoria, Modelo nacional u otra disponible.",
    precio: 45,
    categoria: "bebidas",
  },
  {
    id: "michelada",
    nombre: "Michelada",
    descripcion: "Cerveza preparada con jugo de limón y salsa de la casa.",
    precio: 60,
    categoria: "bebidas",
  },
  {
    id: "chelada",
    nombre: "Chelada",
    descripcion: "Cerveza preparada.",
    precio: 55,
    categoria: "bebidas",
  },
  {
    id: "cubeta-de-5-cervezas",
    nombre: "Cubeta de 5 cervezas",
    descripcion: "5 cervezas nacionales, ideal para compartir.",
    precio: 200,
    categoria: "bebidas",
  },
  {
    id: "cubeta-de-10-cervezas",
    nombre: "Cubeta de 10 cervezas",
    descripcion: "10 cervezas nacionales, ideal para compartir.",
    precio: 360,
    categoria: "bebidas",
  },
  {
    id: "clamato-preparado",
    nombre: "Clamato preparado",
    descripcion: "Preparado con jugo de limón y salsa de la casa.",
    precio: 55,
    categoria: "bebidas",
  },
  {
    id: "cantarito-clasico",
    nombre: "Cantarito Clásico",
    descripcion: "Tequila, toronja, limón y naranja.",
    precio: 120,
    categoria: "bebidas",
  },
  {
    id: "cantarito-paulita",
    nombre: "Cantarito Paulita",
    descripcion: "La versión de la casa.",
    precio: 130,
    categoria: "bebidas",
  },
  {
    id: "cantarito-grande",
    nombre: "Cantarito Grande",
    descripcion: "1 litro para compartir.",
    precio: 240,
    categoria: "bebidas",
  },
  {
    id: "jarra-de-clericot",
    nombre: "Jarra de Clericot",
    descripcion: "Vino blanco, frutas y refresco.",
    precio: 400,
    categoria: "bebidas",
  },
  {
    id: "copa-de-clericot",
    nombre: "Copa de Clericot",
    descripcion: "Vino blanco, frutas y refresco.",
    precio: 150,
    categoria: "bebidas",
  },
  {
    id: "copa-de-vino-tinto",
    nombre: "Copa de vino tinto",
    descripcion: "Vino tinto de la casa.",
    precio: 150,
    categoria: "bebidas",
  },
  {
    id: "copa-de-vino-blanco",
    nombre: "Copa de vino blanco",
    descripcion: "Vino blanco de la casa.",
    precio: 150,
    categoria: "bebidas",
  },
  {
    id: "shot-de-don-julio",
    nombre: "Shot de Don Julio",
    descripcion: "Tequila Don Julio.",
    precio: 250,
    categoria: "shots",
  },
  {
    id: "shot-de-mezcal-400-conejos",
    nombre: "Shot de Mezcal (400 Conejos)",
    descripcion: "Mezcal 400 conejos.",
    precio: 200,
    categoria: "shots",
  },
  {
    id: "shot-de-jack-daniels",
    nombre: "Shot de Jack Daniels",
    descripcion: "Whiskey Jack Daniels.",
    precio: 200,
    categoria: "shots",
  }
];